name = "api"
main = "src/main.ts"
compatibility_date = "2026-05-05"
upload_source_maps = true

[triggers]
crons = ["*/1 * * * *", "0 * * * *"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
persist = true

[observability.traces]
enabled = true
persist = true

[observability.issues]
enabled = true

[observability.issue_detection]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "vita3k-api"
database_id = "ee553ac9-d690-4b67-b9e3-1716a54815a5"